EXPERIMENT:
  NAME: ""
  TAG: "Our_FL_dot,dkd,resnet32x4,wrn_16_2,2"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "CRD"
  TEACHER: "resnet32x4" #"wrn_40_2" # "vgg13" #"resnet32x4"
  STUDENT: "wrn_16_2" # vgg8" #"resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.025
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "crd_dot" 
DIV:
  USAGE: True
  AUGNUM : 5
  DKD : True
  FEAT_INTERWEIGHT : 0.1
  FEAT_INTRAWEIGHT : 1.0
  LOGIT_INTERWEIGHT : 1.0
  LOGIT_INTRAWEIGHT : 1.0


