EXPERIMENT:
  NAME: ""
  TAG: "Our_FL_2stage,margin0.1,dkd,wrn_40_2,wrn_40_1"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "CRD"
  TEACHER: "wrn_40_2"
  STUDENT: "wrn_40_1"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "crd" 
DKD:
  BETA: 6.0
DIV:
  USAGE: True
  DKD : True
  AUGNUM : 5
  FEAT_INTERWEIGHT : 0.1
  FEAT_INTRAWEIGHT : 1.0
  LOGIT_INTERWEIGHT : 1.0
  LOGIT_INTRAWEIGHT : 1.0