EXPERIMENT:
  NAME: ""
  TAG: "Tekap,dkd,wrn_40_2,res8x4,2"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "CRD"
  TEACHER: "wrn_40_2"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.025
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "crd_dot" 
DKD:
  BETA: 6.0
TEKAP:
  USAGE: True
  AUGNUM : 3
  T : 4
  FEAT : True
  LOGIT : True
  DKD : True

