EXPERIMENT:
  NAME: ""
  TAG: "Ours_L,temp=1,A6000,crd,res34,res18"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "CRD"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 110
  LR: 0.1
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "crd" 
KD:
  TEMPERATURE: 1.0
CRD:
  FEAT:
    STUDENT_DIM: 512
    TEACHER_DIM: 512
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
DIV:
  USAGE: True
  AUGNUM : 5
  FEAT_INTERWEIGHT : 0.0
  FEAT_INTRAWEIGHT : 0.0
  LOGIT_INTERWEIGHT : 1.0
  LOGIT_INTRAWEIGHT : 1.0

