EXPERIMENT:
  NAME: ""
  TAG: "tekap,MLKD,vgg13,mv2"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "CRD_tekap"
  TEACHER: "vgg13"
  STUDENT: "MobileNetV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 480
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "crd_aug" 
TEKAP:
  USAGE: True
  AUGNUM : 3
<<<<<<< HEAD
  T : 4
=======
  T : 4
>>>>>>> 398197a3ccbc45b2f6dfe5e9b68991bbd45a9fa8
