EXPERIMENT:
  NAME: ""
  TAG: "Our_F,Our_L,mlkd,resnet32x4,ShuffleV2"
  PROJECT: "cifar100_baselines_epoch960"
DISTILLER:
  TYPE: "CRD_mlkd"
  TEACHER: "resnet32x4"
  STUDENT: "ShuffleV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 960
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "crd_aug" 
DIV:
  USAGE: True
  MLKD : True
  AUGNUM : 5
  FEAT_INTERWEIGHT : 0.1
  FEAT_INTRAWEIGHT : 1.0
  LOGIT_INTERWEIGHT : 1.0
  LOGIT_INTRAWEIGHT : 1.0
