EXPERIMENT:
  NAME: ""
  TAG: "Rebuttal,kd,wrn40_2,wrn16_2" #res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "KD"
  TEACHER: "wrn_40_2" #"resnet32x4"
  STUDENT: "wrn_16_2" #"resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
