EXPERIMENT:
  NAME: ""
  TAG: "pretrain,resnet32x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "NONE"
  TEACHER: "resnet32x4"  #"wrn_40_2" #"vgg13" #"resnet32x4" 
  STUDENT: "resnet32x4"  #"wrn_40_2" #"vgg13" #"resnet32x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 30
  LR: 0.1
  LR_DECAY_STAGES: [10, 20, 30]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DIV:
  USAGE: True
  AUGNUM : 5
  FEAT_INTERWEIGHT : 0.1
  FEAT_INTRAWEIGHT : 1.0
  LOGIT_INTERWEIGHT : 1.0
  LOGIT_INTRAWEIGHT : 1.0