EXPERIMENT:
  NAME: ""
  TAG: "TeKAP,reviewkd,res32x4,wrn_40_2" #res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "REVIEWKD"
  TEACHER: "resnet32x4"
  STUDENT: "wrn_40_2"
REVIEWKD:
  REVIEWKD_WEIGHT: 5.0
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
TEKAP:
  USAGE: True
  AUGNUM : 3
  T : 4
  FEAT : True
  LOGIT : True
  DKD : True


