EXPERIMENT:
  NAME: ""
  TAG: "Ours_FL,reviewkd,vgg13,MobileNetV2" #res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "REVIEWKD"
  TEACHER: "vgg13" #"resnet32x4"
  STUDENT: "MobileNetV2" #"wrn_40_1" #"resnet8x4"
REVIEWKD:
  REVIEWKD_WEIGHT: 5.0
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "crd_aug" 
DIV:
  USAGE: True
  AUGNUM : 5
  FEAT_INTERWEIGHT : 0.1
  FEAT_INTRAWEIGHT : 1.0
  LOGIT_INTERWEIGHT : 1.0
  LOGIT_INTRAWEIGHT : 1.0

