# EXPERIMENT:
#   NAME: ""
#   TAG: "TeKAP,reviewkd_8.0,res32,res8"
#   PROJECT: "cifar100_baselines"
# DISTILLER:
#   TYPE: "REVIEWKD"
#   TEACHER: "resnet32x4"
#   STUDENT: "resnet8x4"
# REVIEWKD:
#   REVIEWKD_WEIGHT: 8.0
# SOLVER:
#   BATCH_SIZE: 64
#   EPOCHS: 240
#   LR: 0.05
#   LR_DECAY_STAGES: [150, 180, 210]
#   LR_DECAY_RATE: 0.1
#   WEIGHT_DECAY: 0.0005
#   MOMENTUM: 0.9
#   TYPE: "SGD"
# TEKAP:
#   USAGE: True
#   AUGNUM : 3
#   T : 4
#   FEAT : True
#   LOGIT : True
#   DKD : True


EXPERIMENT:
  NAME: ""
  TAG: "Rebuttal,ReviewKD,TeKAP_Full,res32x4,wrn40_2"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "REVIEWKD"
  TEACHER: "resnet32x4"
  STUDENT: "wrn_40_2" #"resnet8x4"
REVIEWKD:
  REVIEWKD_WEIGHT: 8.0
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
TEKAP:
  USAGE: True
  AUGNUM : 3
  T : 3
  FEAT : True
  LOGIT : True